version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sqli_lab
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"

  web:
    build: ./web
    ports:
      - "8088:80"
    depends_on:
      - db
